### ISSUE TITLE
FinDoc Analyzer - Deployment Issues and Recommendations

### ISSUE THREAD

**Issue by aviadkim** [aviadkim/backv2#10]
# FinDoc Analyzer - Deployment Issues and Recommendations

## Overview
After thorough testing of the deployed FinDoc Analyzer application at https://findoc-deploy.ey.r.appspot.com, I've identified several critical issues that need to be addressed to ensure proper functionality of the document processing workflow.

### 1. API Endpoint Issues
- The `/api/documents/scan1/status` endpoint returns a 404 error
- The `/api/documents/{id}/scan1` endpoint returns a 404 error
- The `/api/documents/scan1/verify-gemini` endpoint returns the HTML of the main page instead of JSON

### 2. Routing Issues
- The application is serving the main HTML page for API endpoints that should return JSON
- The catch-all route in app.js is intercepting API requests and returning the index.html file

### 3. Deployment Issues
- The application is not properly configured to handle API routes
- The application is not properly configured to handle file uploads

### 4. Python Dependencies
- The Python dependencies required for document processing are not properly installed on the server
- The application is not properly configured to use Python for document processing

### 1. Fix the Routing Issues
```javascript
// Update app.js to properly handle API routes
// Move the catch-all route to the end of the file
app.use('/api/visualizations', visualizationRoutes);
app.use('/api/reports', reportRoutes);
app.use('/api/financial', financialRoutes);
app.use('/api/agents', agentRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/comparisons', comparisonRoutes);
app.use('/api/portfolios', portfolioRoutes);
app.use('/api/documents', documentRoutes);
app.use('/api/chat', chatRoutes);

// Add API 404 handler
app.use('/api/*', (req, res) => {
  res.status(404).json({
    success: false,
    error: 'API endpoint not found'
  });
});

// Catch-all route for SPA (moved to the end)
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, '../public/index.html'));
});
```

### 2. Fix the API Endpoint Issues
```javascript
// Update document routes to properly handle the Scan1 endpoints
// Fix the order of routes to avoid conflicts

// Get Scan1 status - use optional auth to allow public access for status checks
router.get('/scan1/status', optionalAuthMiddleware, getScan1Status);

// Verify Gemini API key
router.get('/scan1/verify-gemini', authMiddleware, verifyGeminiApiKey);

// Get document by ID
router.get('/:id', authMiddleware, getDocumentById);

// Process document with Scan1
router.post('/:id/scan1', authMiddleware, processDocumentWithScan1);
```

### 3. Fix the Deployment Issues
```yaml
# Update app.yaml to properly configure the application
runtime: nodejs18

instance_class: F2

env_variables:
  NODE_ENV: "production"
  SUPABASE_URL: "https://dnjnsotemnfrjlotgved.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuam5zb3RlbW5mcmpsb3RndmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODI0MzQ4NjcsImV4cCI6MTk5ODAxMDg2N30.t2oGhMPXxeY9jrQq5E7VDfGt2Vf_AgeStBjQfqfcBjY"
  GEMINI_API_KEY: "YOUR_GEMINI_API_KEY"
  JWT_SECRET: "findoc-secret-key"

handlers:
  - url: /api/.*
    script: auto
    secure: always
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
```

### 4. Fix the Python Dependencies
```dockerfile
# Update Dockerfile to properly install Python dependencies
# Use the official Node.js 18 image as a parent image
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Install Python and other dependencies for PDF processing
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    build-essential \
    ghostscript \
    poppler-utils \
    libpoppler-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip3 install camelot-py[cv] PyPDF2 pandas numpy matplotlib pymupdf

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy the rest of the application code
COPY . .

# Create temp directory for processing
RUN mkdir -p /app/temp

# Expose the port the app runs on
EXPOSE 8080

# Start the application
CMD ["npm", "start"]
```

## Implementation Timeline
- Day 1: Fix routing issues and API endpoint issues
- Day 2: Fix deployment issues and Python dependencies
- Day 3: Test end-to-end functionality

## Expected Outcomes
- Users can authenticate and access the application
- Documents can be uploaded and processed with Scan1
- Gemini API key is properly verified and used for processing
- Documents and user data are properly stored in the database
- Agents can answer questions about processed documents
- Database maintains all data with proper tenant isolation
